### ISSUE TITLE
EACCES: permission denied, mkdir nest-chat-realtime/dist

### ISSUE THREAD

**Issue by kachar** [phatvo21/nest-chat-realtime#1]
Hi there

While starting the container I've experienced the following

`docker-compose up`

```
nestchat    | [9:18:53 AM] Starting compilation in watch mode...
nestchat    | 
nestchat    | error TS5033: Could not write file '/var/www/nest-chat-realtime/dist/adapters/redis.adapter.d.ts': EACCES: permission denied, mkdir '/var/www/nest-chat-realtime/dist'.
nestchat    | 
nestchat    | error TS5033: Could not write file '/var/www/nest-chat-realtime/dist/adapters/redis.adapter.js': EACCES: permission denied, mkdir '/var/www/nest-chat-realtime/dist'.
nestchat    | 
nestchat    | error TS5033: Could not write file '/var/www/nest-chat-realtime/dist/adapters/redis.adapter.js.map': EACCES: permission denied, mkdir '/var/www/nest-chat-realtime/dist'.
...

nestchat    | [9:20:25 AM] File change detected. Starting incremental compilation...
nestchat    | error TS5033: Could not write file '/var/www/nest-chat-realtime/dist/adapters/redis.adapter.d.ts': EACCES: permission denied, mkdir '/var/www/nest-chat-realtime/dist/adapters'.
...
```

Have you noticed that while running the container?

---

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

**Comment by phatvo21** [comment]
Hi Ilko, 
It working well on my side. I'm running the application on macOS and centOS 7. 
So, both machines working well as I've checked. As you can see the screenshot attached below.
What's operating system are you using? 
And, also there might be a Docker configure permission which is located on your machine. 
Please have a double-check those two things mentioned. 
<img width="1406" alt="Screenshot 2020-11-04 at 16 49 39" src="https://user-images.githubusercontent.com/30039458/98096602-893c9300-1ebe-11eb-8ca8-6010c8d09926.png">

**Comment by kachar** [comment]
The problem was caused by the following lines inside the Dockerfile.

```Dockerfile
# grant a permission to the application
RUN chown -R chat:chat /var/www/nest-chat-realtime
USER chat
```

When I removed the custom user and rebuilt the container I was able to share the dist folder with the host.


Thanks for the help and sorry for the lack of info on the report.

**Comment by shubumpc91** [comment]
> The problem was caused by the following lines inside the Dockerfile.
> 
> ```dockerfile
> # grant a permission to the application
> RUN chown -R chat:chat /var/www/nest-chat-realtime
> USER chat
> ```
> 
> When I removed the custom user and rebuilt the container I was able to share the dist folder with the host.
> 
> Thanks for the help and sorry for the lack of info on the report.

I am facing the same issue. 
What was replaced with the custom User ```chat```?
